name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: raptazure/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: https://gist.github.com/leolanger/79a252249c9f5c3d7a4ade895a532617
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
